In [15]:
import torch

 三维数组的拼接

In [24]:
X = torch.arange(24, dtype=torch.float32).reshape((2,3,4))
Y = torch.tensor([[[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]],[[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
Z= torch.ones(2,3,4)
torch.cat((X, Y, Z), dim=2),torch.cat((X, Y, Z), dim=1),torch.cat((X, Y, Z), dim=0)

(tensor([[[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.,  1.,  1.,  1.,  1.],
          [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.,  1.,  1.,  1.,  1.],
          [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.,  1.,  1.,  1.,  1.]],
 
         [[12., 13., 14., 15.,  2.,  1.,  4.,  3.,  1.,  1.,  1.,  1.],
          [16., 17., 18., 19.,  1.,  2.,  3.,  4.,  1.,  1.,  1.,  1.],
          [20., 21., 22., 23.,  4.,  3.,  2.,  1.,  1.,  1.,  1.,  1.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [ 2.,  1.,  4.,  3.],
          [ 1.,  2.,  3.,  4.],
          [ 4.,  3.,  2.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [ 2.,  1.,  4.,  3.],
          [ 1.,  2.,  3.,  4.],
          [ 4.,  3.,  2.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,

广播机制条件：
tensor维度相等。
tensor维度不等且其中一个维度为1。
tensor维度不等且其中一个维度不存在。

In [38]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1,2))
a,b
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

处理订书名单人工数据集

In [5]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'Booking List.csv')
with open(data_file, 'w') as f:
    f.write('Name,Booknum,Price\n')  # 列名
    f.write('NA,1111,11.11\n')  # 每行表示一个数据样本
    f.write('Zhangsan,2222,12.12\n')
    f.write('Lisi,3333,NA\n')
    f.write('Tianliu,4444,60.00\n')
import pandas as pd

data = pd.read_csv(data_file)
print(data)

       Name  Booknum  Price
0       NaN     1111  11.11
1  Zhangsan     2222  12.12
2      Lisi     3333    NaN
3   Tianliu     4444  60.00


插值法插入姓名

In [6]:
data['Name'].fillna("Wangwu",inplace=True)
print(data)

       Name  Booknum  Price
0    Wangwu     1111  11.11
1  Zhangsan     2222  12.12
2      Lisi     3333    NaN
3   Tianliu     4444  60.00


用均值替代金额

In [7]:
data['Price'].fillna(data['Price'].mean(),inplace=True)
data

Name  Booknum      Price
0    Wangwu     1111  11.110000
1  Zhangsan     2222  12.120000
2      Lisi     3333  27.743333
3   Tianliu     4444  60.000000

删除第一列

In [8]:
data.drop('Name',axis=1,inplace=True)
data

Booknum      Price
0     1111  11.110000
1     2222  12.120000
2     3333  27.743333
3     4444  60.000000

转换为张量格式

In [17]:
booknum,price=data.iloc[:,0],data.iloc[:,1]
x,y=torch.tensor(booknum.values),torch.tensor(price.values)
x,y

(tensor([1111, 2222, 3333, 4444]),
 tensor([11.1100, 12.1200, 27.7433, 60.0000], dtype=torch.float64))