In [7]:
import torch

 三维数组的拼接

In [24]:
X = torch.arange(24, dtype=torch.float32).reshape((2,3,4))
Y = torch.tensor([[[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]],[[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
Z= torch.ones(2,3,4)
torch.cat((X, Y, Z), dim=2),torch.cat((X, Y, Z), dim=1),torch.cat((X, Y, Z), dim=0)

(tensor([[[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.,  1.,  1.,  1.,  1.],
          [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.,  1.,  1.,  1.,  1.],
          [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.,  1.,  1.,  1.,  1.]],
 
         [[12., 13., 14., 15.,  2.,  1.,  4.,  3.,  1.,  1.,  1.,  1.],
          [16., 17., 18., 19.,  1.,  2.,  3.,  4.,  1.,  1.,  1.,  1.],
          [20., 21., 22., 23.,  4.,  3.,  2.,  1.,  1.,  1.,  1.,  1.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [ 2.,  1.,  4.,  3.],
          [ 1.,  2.,  3.,  4.],
          [ 4.,  3.,  2.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [ 2.,  1.,  4.,  3.],
          [ 1.,  2.,  3.,  4.],
          [ 4.,  3.,  2.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.],
          [ 1.,

广播机制条件：
tensor维度相等。
tensor维度不等且其中一个维度为1。
tensor维度不等且其中一个维度不存在。

In [38]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1,2))
a,b
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

处理订书名单人工数据集

In [43]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'Booking List.csv')
with open(data_file, 'w') as f:
    f.write('Name,Booknum,Price\n')  # 列名
    f.write('NA,1111,11.11\n')  # 每行表示一个数据样本
    f.write('Zhangsan,NA,12.12\n')
    f.write('Lisi,NA,45.50\n')
    f.write('NA,NA,60.00\n')
import pandas as pd

data = pd.read_csv(data_file)
print(data)

       Name  Booknum  Price
0       NaN   1111.0  11.11
1  Zhangsan      NaN  12.12
2      Lisi      NaN  45.50
3       NaN      NaN  60.00


In [61]:
newlist = data.fillna(value={0:"Wangwu",3:"Tianliu"},axis=0)
print(newlist)

       Name  Booknum  Price
0       NaN   1111.0  11.11
1  Zhangsan      NaN  12.12
2      Lisi      NaN  45.50
3       NaN      NaN  60.00
