# 尝试部分

In [1]:
import torch

生成一个较例子更大的6*5的矩阵

In [44]:
A = torch.arange(30,dtype=torch.float32).reshape(6,5 )
A

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]])

生成一个B，随机为1到10的整数

In [45]:
B= torch.randint(1, 11, dtype=torch.float32,size=(6, 5))
B

tensor([[ 1.,  6.,  2.,  9.,  1.],
        [ 5., 10.,  3., 10.,  6.],
        [ 5., 10., 10.,  3.,  1.],
        [ 7.,  9.,  8.,  1.,  8.],
        [ 2.,  3.,  7.,  2., 10.],
        [10.,  3.,  6., 10.,  4.]])

基本运算

In [10]:
A*B,2+A,2*A

(tensor([[  0.,   2.,  14.,  27.,  12.],
         [ 45.,  48.,  56.,  72.,  90.],
         [ 20., 110.,  48.,  78.,  42.],
         [105.,  32., 153., 126.,  19.],
         [140., 168., 176., 138.,  72.],
         [250., 130., 216., 224.,  58.]]),
 tensor([[ 2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16.],
         [17., 18., 19., 20., 21.],
         [22., 23., 24., 25., 26.],
         [27., 28., 29., 30., 31.]]),
 tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.],
         [40., 42., 44., 46., 48.],
         [50., 52., 54., 56., 58.]]))

降维

In [31]:
B_sum_axis0 = B.sum(axis=0)
B_sum_axis1 = B.sum(axis=1)
B.sum(),B_sum_axis0, B_sum_axis0.shape,B_sum_axis1, B_sum_axis1.shape,A.mean()

(tensor(188),
 tensor([42, 35, 44, 45, 22]),
 torch.Size([5]),
 tensor([28, 44, 25, 26, 32, 33]),
 torch.Size([6]),
 tensor(19.5000))

点积

In [46]:
A=A[1:,:]
torch.mm(B, A)

tensor([[300., 319., 338., 357., 376.],
        [520., 554., 588., 622., 656.],
        [360., 389., 418., 447., 476.],
        [465., 498., 531., 564., 597.],
        [435., 459., 483., 507., 531.],
        [470., 503., 536., 569., 602.]])

In [48]:
torch.norm(B)

tensor(36.2491)

# 习题部分

1.证明一个矩阵 𝐀
 的转置的转置是 𝐀
 ，即 (𝐀⊤)⊤=𝐀
 。

In [50]:
A.T.T == A

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


2.给出两个矩阵 𝐀
 和 𝐁
 ，证明“它们转置的和”等于“它们和的转置”，即 𝐀⊤+𝐁⊤=(𝐀+𝐁)⊤
 。

In [54]:
A= torch.randint(1, 11, dtype=torch.float32,size=(6, 5))
B= torch.randint(1, 11, dtype=torch.float32,size=(6, 5))
A.T+B.T == (A+B).T

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True]])

3.给定任意方阵 𝐀
 ， 𝐀+𝐀⊤
 总是对称的吗?为什么?

In [58]:
A= torch.randint(1, 11, dtype=torch.float32,size=(5, 5))
A+A.T,A+A.T == (A+A.T).T

(tensor([[16., 10., 11., 11.,  7.],
         [10., 10., 19., 14.,  6.],
         [11., 19.,  2.,  8., 14.],
         [11., 14.,  8.,  4., 16.],
         [ 7.,  6., 14., 16.,  4.]]),
 tensor([[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]))

总是对称的，因为(A+A.T).T=A.T+A

4.对于任意形状的张量X,len(X)是否总是对应于X特定轴的长度?这个轴是什么?

In [62]:
X= torch.randint(1, 11, dtype=torch.float32,size=(2,3,4))
len(X)

2

5.运行A/A.sum(axis=1)，看看会发生什么。请分析一下原因？

In [65]:
A= torch.randint(1, 11, dtype=torch.float32,size=(5, 5))
A,A/A.sum(axis=1)

(tensor([[ 8.,  6.,  7., 10., 10.],
         [ 5.,  2.,  6.,  7.,  6.],
         [ 1.,  7.,  8., 10.,  5.],
         [ 7.,  3.,  7.,  5.,  7.],
         [ 8.,  6.,  3.,  4.,  5.]]),
 tensor([[0.1951, 0.2308, 0.2258, 0.3448, 0.3846],
         [0.1220, 0.0769, 0.1935, 0.2414, 0.2308],
         [0.0244, 0.2692, 0.2581, 0.3448, 0.1923],
         [0.1707, 0.1154, 0.2258, 0.1724, 0.2692],
         [0.1951, 0.2308, 0.0968, 0.1379, 0.1923]]))

产生一个仍是原大小的矩阵，因为广播，复制原来一列五行为五列五行进行除法

6.考虑一个具有形状 (2,3,4)
 的张量，在轴0、1、2上的求和输出是什么形状?

In [66]:
A = torch.arange(24).reshape(2, 3, 4)
print("原始张量：")
print(A)

sum0 = A.sum(dim=0)
print("在轴0上求和：")
print(sum0)
print("形状：", sum0.shape)

sum1 = A.sum(dim=1)
print("在轴1上求和：")
print(sum1)
print("形状：", sum1.shape)

sum2 = A.sum(dim=2)
print("在轴2上求和：")
print(sum2)
print("形状：", sum2.shape)

sum_all = A.sum(dim=(0, 1, 2))
print("在轴0、1、2上同时求和：")
print(sum_all)

原始张量：
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
在轴0上求和：
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
形状： torch.Size([3, 4])
在轴1上求和：
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
形状： torch.Size([2, 4])
在轴2上求和：
tensor([[ 6, 22, 38],
        [54, 70, 86]])
形状： torch.Size([2, 3])
在轴0、1、2上同时求和：
tensor(276)


7.为linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?

In [69]:
A = torch.arange(24,dtype=torch.float32).reshape(2, 3, 4)
print("原始张量：")
print(A)

norm = torch.linalg.norm(A)
print("Frobenius范数：")
print(norm)

原始张量：
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
Frobenius范数：
tensor(65.7571)


计算这个张量的范数